// Generated by gencpp from file signal_chassis/DrivetrainStamped.msg
// DO NOT EDIT!


#ifndef SIGNAL_CHASSIS_MESSAGE_DRIVETRAINSTAMPED_H
#define SIGNAL_CHASSIS_MESSAGE_DRIVETRAINSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <signal_chassis/Drivetrain.h>

namespace signal_chassis
{
template <class ContainerAllocator>
struct DrivetrainStamped_
{
  typedef DrivetrainStamped_<ContainerAllocator> Type;

  DrivetrainStamped_()
    : header()
    , data()  {
    }
  DrivetrainStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::signal_chassis::Drivetrain_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> const> ConstPtr;

}; // struct DrivetrainStamped_

typedef ::signal_chassis::DrivetrainStamped_<std::allocator<void> > DrivetrainStamped;

typedef boost::shared_ptr< ::signal_chassis::DrivetrainStamped > DrivetrainStampedPtr;
typedef boost::shared_ptr< ::signal_chassis::DrivetrainStamped const> DrivetrainStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_chassis::DrivetrainStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::signal_chassis::DrivetrainStamped_<ContainerAllocator1> & lhs, const ::signal_chassis::DrivetrainStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::signal_chassis::DrivetrainStamped_<ContainerAllocator1> & lhs, const ::signal_chassis::DrivetrainStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace signal_chassis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c649390f2093016370e2a72d846e0f4a";
  }

  static const char* value(const ::signal_chassis::DrivetrainStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc649390f20930163ULL;
  static const uint64_t static_value2 = 0x70e2a72d846e0f4aULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_chassis/DrivetrainStamped";
  }

  static const char* value(const ::signal_chassis::DrivetrainStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Drivetrain data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: signal_chassis/Drivetrain\n"
"float32 steer_angle_fl\n"
"float32 steer_angle_fr\n"
"float32 steer_angle_rl\n"
"float32 steer_angle_rr\n"
"float32 drive_speed_fl\n"
"float32 drive_speed_fr\n"
"float32 drive_speed_rl\n"
"float32 drive_speed_rr\n"
"float32 drive_angular_speed_fl\n"
"float32 drive_angular_speed_fr\n"
"float32 drive_angular_speed_rl\n"
"float32 drive_angular_speed_rr\n"
"int32 motion_mode\n"
;
  }

  static const char* value(const ::signal_chassis::DrivetrainStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrivetrainStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_chassis::DrivetrainStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_chassis::DrivetrainStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::signal_chassis::Drivetrain_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_CHASSIS_MESSAGE_DRIVETRAINSTAMPED_H
